__default__:
  account: def-scottmic
  mail-user: kristina.song@usherbrooke.ca
  mail-type: FAIL
  job-name: "smk_{rule}_{wildcards}"
  time: 180 # minutes
  mem: 16000M
  cpus-per-task: 8
  output: results/logs/slurmout/{rule}.{wildcards}.out
  error: results/logs/slurmout/{rule}.{wildcards}.err
  

sno_RBP_overlap:
  time: 4320
  cpus-per-task: 44
  mem: 191840M
