---
data:
  rbp_ENCODE: ../network_data/ENCODE_RBP/
  rbp_formatted: ../network_data/ENCODE_RBP_formatted/
  snoglobe: ../network_data/snoglobe_predictions/
  snoglobe_formatted: ../network_data/snoglobe_formatted/
  snoRNA_list : ../network_data/snoRNA.tsv
  ENCODE_rbp_list : ../network_data/ENCODE_rbp_list.tsv
  rbp_list : ../network_data/rbp.tsv
  rbp_list_with_protein_id : ../network_data/rbp_protein_id.tsv
  annotation: ../network_data/hg38_Ensembl_V101_Scottlab_2020.tsv
  chrLength: ../network_data/chrNameLength.txt
  snoDB: ../network_data/snoDB.tsv
  STRING: ../network_data/STRING.9606.protein.actions.v11.0.txt.gz
  HTRRI: ../network_data/htrri_interactions_P_L_S.tsv
  tpm: ../network_data/coco_tpm.tsv

ENCODE_p_threshold: 3
ENCODE_sig_val_threshold: 3
STRING_score_threshold: 900
ovlp_p_val_threshold: 100000

logs: ../network_data/logs/
temp: ../network_data/temp/

outpath: ../network_output/