---
path:
  gtf: /home/kris98/scratch/annotation_datasets/Homo_sapiens.GRCh38.110_snoRNAs_tRNAs.gtf
  snoDB: /home/kris98/scratch/annotation_datasets/snoDB_All_V2.0.tsv
  tpm: /home/kris98/scratch/annotation_datasets/TGIRT_Seq_v110_cell_lines/coco_cc/homo_sapiens_merged_tpm.tsv
  ENCODE: /home/kris98/scratch/annotation_datasets/ENCODE_RBP_2023/
  snoglobe: /home/kris98/scratch/run_snoglobe/snoglobe_predictions_2024/
  chrNameLength: /home/kris98/scratch/annotation_datasets/star_index/chrNameLength.txt
  STRING_interactions: /home/kris98/scratch/annotation_datasets/STRING_v12/9606.protein.physical.links.v12.0.txt.gz
  STRING_info: /home/kris98/scratch/annotation_datasets/STRING_v12/9606.protein.info.v12.0.txt.gz
  HTRRI: /home/kris98/scratch/annotation_datasets/htrri_crssant.tsv
  snoRNA_list: /home/kris98/scratch/annotation_datasets/filtered_genes/sig_exp_CD_snoRNAs.tsv
  RBP_list: /home/kris98/scratch/annotation_datasets/filtered_genes/exp_RBPs.tsv
  virtualenv: /home/kris98/venv3.11/bin/activate
  exp_pc_genes: /home/kris98/scratch/annotation_datasets/filtered_genes/exp_pc_genes.tsv
